
spring:
  # Config thymeleaf
  thymeleaf:
    cache: false
  # Config MYSQL
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/db_bus_tickets
  # Config hibernate
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true